language: java
jdk:
  - openjdk8
before_install:
  - chmod +x gradlew
branches: # 1번
  only:
    - master
# Travis CI 서버의 Home
cache: # 2번
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"  # 3번

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip
deploy:
  - provider: s3
    access_key_id: AKIA4PAY5UU4VMHS4TMJ # Travis repo settings에 설정된 값
    secret_access_key: 0i9ohKefHJctq5+dO3qg2Wakj3ebMSVrDU3dPoSS # Travis repo settings에 설정된 값
    bucket: picturespot # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIA4PAY5UU4VMHS4TMJ # Travis repo settings에 설정된 값
    secret_access_key: 0i9ohKefHJctq5+dO3qg2Wakj3ebMSVrDU3dPoSS # Travis repo settings에 설정된 값
    bucket: picturespot # S3 버킷
    key: freelec-springboot2-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: freelec-springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: freelec-springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:  # 4번
  email:
    recipients:
      - epfvkdlxj@naver.com




        # 주석
        # 1번 :branches
        # - Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정한다.
        # - 현재옵션은 오직 master 브랜치에 push될 때만 수행한다.
        # 2번 :cache
        # - 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정한다.
        # 3번 :script
        # - master 브랜치에 푸시되었을 때 수행하는 명령어이다.
         # - 여기서는 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행한다.

      #  - zip -r freelec-springboot2-webservice *
      #  - mkdir -p deployㅏ
      #  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip
